version: "3.9"

services:
  db:
    image: postgres:16-alpine
    environment:
      POSTGRES_DB: spendo
      POSTGRES_USER: spendo
      POSTGRES_PASSWORD: spendo
    command: [ "postgres",
               "-c", "shared_buffers=64MB",
               "-c", "work_mem=4MB",
               "-c", "max_connections=20",
               "-c", "effective_cache_size=256MB" ]

    volumes:
      - dbdata:/var/lib/postgresql/data
      - ./db/init.sql:/docker-entrypoint-initdb.d/00_init.sql:ro
    healthcheck:
      test: ["CMD-SHELL", "pg_isready -U spendo -d spendo"]
      interval: 5s
      timeout: 3s
      retries: 20
    ports:
      - "5432:5432"

  api:
    build: ./api
    environment:
      DATABASE_URL: postgresql://spendo:spendo@db:5432/spendo
    depends_on:
      db:
        condition: service_healthy
    ports:
      - "8000:8000"
    command: >
      uvicorn app.main:app --host 0.0.0.0 --port 8000

  web:
    build: ./web
    depends_on:
      - api
    ports:
      - "3000:3000"
    command: ["npm", "run", "preview", "--", "--host", "0.0.0.0", "--port", "3000"]

volumes:
  dbdata:
